### ISSUE TITLE
Modified highlight color via custom css doesn't work inside admoniton block in live-preview

### ISSUE THREAD

**Issue by kataowl** [valentine195/obsidian-admonition#140]
I have a custom css to change to the highlight color like this:

```css
.cm-highlight
{
    color: black !important;
    background: rgb(139, 245, 118) !important;
}

.markdown-preview-view mark
{
    color: black !important;
    background: rgb(139, 245, 118) !important;
}
```

But this new highlight color isn't applied to the highlight inside admonition in live-preview mode:

![image](https://user-images.githubusercontent.com/94876576/147148640-d6eb408a-2d84-4637-9e72-d6908f7934c2.png)

It works well in preview mode.
