### ISSUE TITLE
Admonition formatting looks odd in live preview mode—huge spacing

### ISSUE THREAD

**Issue by lukthony** [valentine195/obsidian-admonition#141]
This is in a fresh vault, Admonition is the only plug-in installed, Obsidian v0.13.4, Admonition v6.7.2

Preview(expected behavior):
<img width="750" alt="Screen Shot 2021-12-22 at 5 27 02 PM" src="https://user-images.githubusercontent.com/65358837/147166177-823d3c5c-830d-4903-838f-9b3f602afb4f.png">

Live Preview (actual behavior):
<img width="755" alt="Screen Shot 2021-12-22 at 5 26 56 PM" src="https://user-images.githubusercontent.com/65358837/147166222-eb7a0d3c-8abe-437b-b3a2-1ea8be9811a8.png">

**Comment by red0orange** [comment]
I also meet this problem.

**Comment by valentine195** [comment]
This is likely just a plugin CSS problem, will investigate and fix once I get a chance.

**Comment by red0orange** [comment]
Thank you and Merry Christmas!

**Comment by GOUKOU007** [comment]
This problem can be  temporarily fixed by add following css snippet in snippet folder:
```css
.is-live-preview .admonition-content>p {
    margin: 0px;
}

.is-live-preview .admonition-content>p:first-child {
    margin-top: 16px;
}

.admonition-content>p:last-child {
    margin-bottom: 16px;
}
```
