### ISSUE TITLE
It would be nice to make a custom color for the title which is separate from the text color of the note contents.

### ISSUE THREAD

**Issue by brandon-kohn** [valentine195/obsidian-admonition#169]

**Comment by valentine195** [comment]
You can do this with CSS... not sure I want to clutter the Admonition creation modal more.

```css
.admonition-note .admonition-title {
   color: <color>
}
```
