### ISSUE TITLE
Decrease padding on admonitions with no title

### ISSUE THREAD

**Issue by jiri** [valentine195/obsidian-admonition#185]
I know this is a very stylistic choice and bikeshedding, but I think it's worth incorporating 😄 I currently use the following CSS tweak to remove the padding when the admonition has no title. see the attached screenshots for the distinction.

```css
.admonition-plugin > .no-title + .admonition-content-holder {
    margin-top: 0 !important;
    margin-bottom: 0 !important;
}

.admonition-plugin > .no-title + .admonition-content-holder > .admonition-content {
    margin-top: 0;
    margin-bottom: 0;
}
```

Before:
![image](https://user-images.githubusercontent.com/661524/154641240-15a15ebf-e114-4312-b4a1-7b989aeedeb7.png)

After:
![image](https://user-images.githubusercontent.com/661524/154641200-5cc782bf-dc37-4d26-a8b3-f6bdc8ff6e1b.png)

As a side note, it might be nice to include the `no-title` class on the admonition itself, since right now there is no way of styling the outermost `.admonition` div when it has no title.
