### ISSUE TITLE
Is there a way to have less space around the admonition text?

### ISSUE THREAD

**Issue by ReaderGuy42** [valentine195/obsidian-admonition#200]
Really cool plugin, especially combined with the Live Preview mode now :)
However, I feel like there is too much space between the title and the text, and then again the text and the end of the admonition block.

Is there a way to remove these blank lines or at least shrink them somehow?

Thanks!

![image](https://user-images.githubusercontent.com/71895400/156552282-49862303-e968-4609-9b1e-a37fee708931.png)

**Comment by valentine195** [comment]
Sure... Admonition content has a 10px margin on the top and bottom. You can override that with a CSS snippet:

```css
.admonition-content {
    margin-top: 10px;
    margin-bottom: 10px;
}
```

**Comment by ReaderGuy42** [comment]
Thanks, but that doesn't change anything. I'm in Live Preview mode, and I saw in the source that there's a different block for that mode, or maybe I misunderstood that.

**Comment by valentine195** [comment]
That snippet isn't specific enough, you're right. This should work (it does on the help vault for me):

```css
.admonition-content-holder > .admonition-content {
    margin-top: 5px;
    margin-bottom: 5px;
}
```

Sorry about that!

**Comment by ReaderGuy42** [comment]
> Please stick to 1 issue for discoverability!

_Originally posted by @valentine195 in https://github.com/valentine195/obsidian-admonition/issues/204#issuecomment-1059319306_

Sorry! I just saw this one had been closed, so I wasn't sure if you would see my other comment.

Now it works, thank you!!

**Comment by ReaderGuy42** [comment]
Ok, so sorry to re-open this for a third time, that second snippet does reduce the white space/margins, but there is still a significant amount of dead space and I already have it set to `0px`
This is without the snippet:
![image](https://user-images.githubusercontent.com/71895400/156810760-850cfc8b-f182-4ec8-a5c4-4270ee1fee58.png)

This is with the snippet enabled:
![image](https://user-images.githubusercontent.com/71895400/156810671-12820293-4268-43a0-b141-ef846483c8f4.png)


Is there some way to further the reduce the margins?
Thanks!

**Comment by valentine195** [comment]
That is probably driven by the paragraph element that the content is rendered as. You could do something like:

```css
.admonition-content > *:first-child {
    margin-top: 0px;
}
.admonition-content > *:last-child {
    margin-bottom: 0px;
}
```
