### ISSUE TITLE
Call-out colors

### ISSUE THREAD

**Issue by DutchPete** [valentine195/obsidian-admonition#221]
I don't know if I should ask you, so if I should not please point me in the right direction.

In the screenshot I have a test Admonition showing the code and the Live Preview rendering, as well as a Call-Out.

![image](https://user-images.githubusercontent.com/10794265/158585958-9025fcbb-6a5a-4d75-95c2-e7fabfb7d3ba.png)

This is what I have as Call-Out code:

![image](https://user-images.githubusercontent.com/10794265/158586123-f12d5c96-d96d-4bba-86f4-74d01a36d627.png)

How can I change the color of the header and text to be like in the Admonition?
I have this snippet:
```css
.callout[data-callout="my-callout-type"] {
    --callout-color: 0, 0, 105;
}
```

I suspect "my-callout-type" is wrong, so I tried to change it to "Alsatian-dog" but it does not work.

Also, what is the syntax to collapse? I have not been able to find it.

**Comment by valentine195** [comment]
Change `my-callout-type` to `note` and it should work. 

Callouts can be made collapsible with a + or - after the brackets - `> [!note]+`

**Comment by DutchPete** [comment]
Thank you, collapse works now.

```css
.callout[data-callout="note"] {
    --callout-color: rgb(0, 0, 105) !important;
}
```

still does not do the trick, even if I delete the quotation marks.

**Comment by valentine195** [comment]
> --callout-color: rgb(0, 0, 105) !important;

This is incorrect, the color has to be defined as `0, 0, 105`

**Comment by DutchPete** [comment]
It does not work in the theme I am using. I tried it in a default theme with no other snippets or plug-ins, and it works, i.e. it is rendered as the Admonition, so it is the theme I am using.

Nevertheless, the text color does not change, it remains black, even with `!important`.

**Comment by valentine195** [comment]
>  the text color does not change

Text color is changed with the `color` CSS property, it does not use the `--callout-color` custom property.

**Comment by valentine195** [comment]
>  the text color does not change

Text color is changed with the `color` CSS property, it does not use the `--callout-color` custom property.

**Comment by DutchPete** [comment]
I am confused now. This snippet:

```css
.callout[data-callout="note"] {
    --callout-color: 255, 0, 0 !important;
    color: rgb(255, 0, 0) !important;
}
```

does not change a thing in the call out.

**Comment by valentine195** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/38669521/158634802-010661d0-3d35-48ea-bda3-46aa301356fe.png)

I recommend testing this in the help vault.

**Comment by DutchPete** [comment]
In the Help vault with that red/red snippet:

![image](https://user-images.githubusercontent.com/10794265/158637639-c346831f-d7e7-4ef5-876b-d979d0097654.png)

![image](https://user-images.githubusercontent.com/10794265/158637755-1ba535d5-5dfe-48e5-a33d-db0489b7d390.png)

**Comment by valentine195** [comment]
Are you targeting like this?

```css
.callout[data-callout="Alsatian dog"]
```

The data tag is lowercased and slugified. You have to target it like this:

```css
.callout[data-callout="alsatian-dog"]
```

**Comment by DutchPete** [comment]
I was doing:

```css
.callout[data-callout="note"] {
    --callout-color: 255, 0, 0 !important;
    color: rgb(255, 0, 0) !important;
}
```

but when I replace *note* with *alsatian dog* (between the quotation marks, of course) still nothing happens. This is in the Help vault.

**Comment by valentine195** [comment]
I'm sorry, they both work for me. Do you have the snippet enabled? If so, I'm really not able to help debug callout issues, they are wholly unrelated to the plugin. You might have more luck on the forum or on the discord.

**Comment by valentine195** [comment]
No worries, I hope you figure it out, it's certainly very weird.

**Comment by DutchPete** [comment]
Just to follow up: I checked in the dev tools (Elements) and found that this also works:

/* change color of title */
```css
.callout-title-inner {
    color: var(--text-normal);
}
```

/* change color of text */
```css
.callout-content {
    color: var(--text-normal);
}
```

I was not able to determine how to change the background color, although you have shown above that the code you provided does work.
