### ISSUE TITLE
[Enhancement Req] Ability to copy content portion.

### ISSUE THREAD

**Issue by MartynKeigher** [valentine195/obsidian-admonition#28]
Hey! 

I have started to use this plugin for some of the short, more 1-liner, code snippets as it looks much nicer than a code-block in a larger document. So having the ability to COPY, just the content, would be a nice addition to this plugin!

I know this was probably not an expected use case for this plugin, but having the ability to toggle on\off a copy feature on it (in it settings) for the few of us that could use it this way... would be amazing!! 

://mk.

**Comment by valentine195** [comment]
## 4.1.0
 Added a copy content setting. This setting adds a "copy" button to all admonitions.

**Comment by MartynKeigher** [comment]
Hey @valentine195  - Thank you so much for adding this feature... and wow.. quick turnaround!! :) 

Amazing time save for me and it works great!

I was playing around with some CSS and I was looking to have the icon appear only when it's hovered over, but as the icon is small... I was wanting the 'content' area to trigger the opacity change... Here is my current code, that while it works.. only 'reveal's the icon when  hover over IT, what addition do I need to the make to the following code so that when i hover over the content area... it then shows the copy icon?

```css
/********************/
/* Admonition tweak */
/********************/

.admonition-content {
  padding-top: 15px;
}

.admonition-content-copy {
  margin: 15px 0px;
  opacity: 0;
  transition: 0.2s all ease-in;
}

.admonition-content-copy:hover {
  opacity: 1;
}
```
(You can ignore the 'padding-top', that was just to add a little space between the content and the title border. (Makes the text appear more 'centrally' (vertically) in its area.


Thanks so much!

**Comment by valentine195** [comment]
Also, the margin you have set on the ```css .admonition-content-copy``` class will cause it to render 15px from the top of block. Not sure if that's what you were intending.

If you want it centered on the content box, try this:

```css
.admonition-content-copy {
    margin: 0px;
    top: 50%;
    transform: translateY(-50%);
    /* ... */
}
```
