### ISSUE TITLE
Edit mode cannot display carriage return

### ISSUE THREAD

**Issue by lians0** [valentine195/obsidian-admonition#282]
In edit mode cannot display carriage return.
![image](https://user-images.githubusercontent.com/30581350/211155914-608aec2d-b16b-4906-ae10-92a517abf1ac.png)

preview mode is normal
![image](https://user-images.githubusercontent.com/30581350/211155969-0e5d4ebe-3f8e-4c89-88f3-cadeef1c161b.png)

**Comment by killerkyros** [comment]
i solved it by adding to the custom css this:
```css
.cm-content[contenteditable=true] .admonition-content p {
    white-space: break-spaces;
}
```
hope it helps
