### ISSUE TITLE
option to remove the folding/collapsing triangle on the left

### ISSUE THREAD

**Issue by scorius13** [valentine195/obsidian-admonition#32]
Thanks for this amazing plugin! Is it possible to add an option to remove the triangle on the left of the admonition when `collapse` is enabled? I remember it wasn't there before version 4.1.0 or something. For me, the indicator on the right is more than enough. And the triangle is adding this extra layer of padding, which is a little excessive. Thank you!
<img width="559" alt="Screen Shot 2021-05-18 at 11 02 45 PM" src="https://user-images.githubusercontent.com/55903768/118676632-25f8c980-b82e-11eb-9578-3324e93d11f5.png">

**Comment by valentine195** [comment]
Are you on v4.1.4?

**Comment by scorius13** [comment]
v.4.1.6 actually. obsidian 0.12.3

**Comment by valentine195** [comment]
Hmm, odd. Do you happen to have any custom CSS snippets that would override the following?

```css
details.admonition > summary::-webkit-details-marker,
details.admonition > summary::marker {
    display: none;
}
```

This should _not_ be displaying post v4.1.4 (and it's not for me).

**Comment by scorius13** [comment]
no I don't think so. I did thought of that and tested with default css without any snippets. still there

**Comment by valentine195** [comment]
Please try 4.1.7 and let me know if this is fixed.

**Comment by scorius13** [comment]
No unfortunately. I created a new vault with nothing but admonition 4.1.7 enabled. It's still there. 
Although 4.1.7 is working properly without the triangle on my macOS 10.15, but not on my macOS 10.15.7. I wonder if it has to do with the mac version

**Comment by valentine195** [comment]
That's weird! Not sure what would cause the difference - I would assume that only the Chromium version of Obsidian would matter. You have Obsidian 0.12.3 installed on both?

In the meantime, if you don't mind, open the devtools (<kbd>Command</kbd>+<kbd>Option</kbd>+<kbd>I</kbd>), then click this icon:
![image](https://user-images.githubusercontent.com/38669521/118701015-3e8ec280-b7e1-11eb-900d-3d90c7f600d6.png)

then hover over the admonition title summary element. 

It should show the following css applied in the devtools:
```css
details.admonition > summary {
    outline: none;
    display: block !important;
    list-style: none !important;
    list-style-type: none !important;
    min-height: 1rem;
    border-top-left-radius: 0.1rem;
    border-top-right-radius: 0.1rem;
    cursor: pointer;
}
```

Specifically important here are:

```css
    display: block !important;
    list-style: none !important;
    list-style-type: none !important;
```

If those are crossed out, the triangle will display.

Not sure what's going on here, though. Really bizarre.
